# Generated by Django 3.0.7 on 2020-08-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sport',
            field=models.CharField(default='none', max_length=256),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(default='none', max_length=256),
        ),
    ]
