# Generated by Django 3.0.7 on 2020-08-23 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_auto_20200823_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='union_territory',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default=None, max_length=256, validators=[django.core.validators.MinLengthValidator(2, 'Minimum length should be greater than 2')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(default=None, max_length=256, validators=[django.core.validators.MinLengthValidator(2, 'Minimum length should be greater than 2')]),
        ),
    ]
