# Generated by Django 3.1.1 on 2020-09-16 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_delete_user_certificates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_certificates',
        ),
    ]
