# Generated by Django 3.0.7 on 2020-08-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0004_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Rather not say', 'Rather not say')], default='Male', max_length=256),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
