# Generated by Django 3.1.1 on 2020-09-17 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0005_trial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
            ],
        ),
        migrations.AlterField(
            model_name='trial',
            name='max_height',
            field=models.PositiveIntegerField(default=175),
        ),
        migrations.AlterField(
            model_name='trial',
            name='max_weight',
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='trial',
            name='min_height',
            field=models.PositiveIntegerField(default=155),
        ),
        migrations.AlterField(
            model_name='trial',
            name='min_weight',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.CreateModel(
            name='DetailsOfApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why_should_be_selected', models.TextField()),
                ('weight', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('O-', 'O-')], max_length=256)),
                ('disability', models.BooleanField(default=False)),
                ('disability_details', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verification.application')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verification.trial'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
