# Generated by Django 3.1.1 on 2020-09-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0006_auto_20200917_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='certificate',
            field=models.ImageField(upload_to='certificates'),
        ),
    ]
