# Generated by Django 3.0.7 on 2020-08-24 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_achievements',
        ),
    ]
